CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    CREATE TABLE "Shifts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "StartTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "Description" character varying(255),
        CONSTRAINT "PK_Shifts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(100) NOT NULL,
        "Username" character varying(50) NOT NULL,
        "Password" character varying(100) NOT NULL,
        "Role" character varying(20) NOT NULL,
        "Phone" character varying(20),
        "Email" character varying(200),
        "Address" character varying(255),
        "SalaryPerShift" numeric NOT NULL,
        "BaseSalary" numeric NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    CREATE TABLE "Attendances" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ShiftId" integer NOT NULL,
        "Date" timestamp without time zone NOT NULL,
        "CheckIn" timestamp without time zone,
        "CheckOut" timestamp without time zone,
        "OvertimeHours" numeric NOT NULL,
        "Status" character varying(50) NOT NULL,
        "Notes" character varying(500),
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Attendances_Shifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "Shifts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Attendances_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    INSERT INTO "Shifts" ("Id", "Description", "EndTime", "Name", "StartTime")
    VALUES (1, '06:00 - 12:00', INTERVAL '12:00:00', 'Ca sáng', INTERVAL '06:00:00');
    INSERT INTO "Shifts" ("Id", "Description", "EndTime", "Name", "StartTime")
    VALUES (2, '12:00 - 18:00', INTERVAL '18:00:00', 'Ca chiều', INTERVAL '12:00:00');
    INSERT INTO "Shifts" ("Id", "Description", "EndTime", "Name", "StartTime")
    VALUES (3, '18:00 - 22:00', INTERVAL '22:00:00', 'Ca tối', INTERVAL '18:00:00');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    INSERT INTO "Users" ("Id", "Address", "BaseSalary", "CreatedAt", "Email", "FullName", "IsActive", "Password", "Phone", "Role", "SalaryPerShift", "Username")
    VALUES (1, 'VP Công ty', 0.0, TIMESTAMP '2025-01-01T00:00:00', 'admin@company.com', 'Admin', TRUE, 'admin123', '0123456789', 'Admin', 0.0, 'admin');
    INSERT INTO "Users" ("Id", "Address", "BaseSalary", "CreatedAt", "Email", "FullName", "IsActive", "Password", "Phone", "Role", "SalaryPerShift", "Username")
    VALUES (2, 'Hà Nội', 5700000.0, TIMESTAMP '2025-01-01T00:00:00', 'nguyenvana@company.com', 'Nguyễn Văn A', TRUE, '123456', '0909123456', 'Worker', 250000.0, 'worker1');
    INSERT INTO "Users" ("Id", "Address", "BaseSalary", "CreatedAt", "Email", "FullName", "IsActive", "Password", "Phone", "Role", "SalaryPerShift", "Username")
    VALUES (3, 'Hồ Chí Minh', 5700000.0, TIMESTAMP '2025-01-01T00:00:00', 'tranthib@company.com', 'Trần Thị B', TRUE, '123456', '0909987654', 'Worker', 250000.0, 'worker2');
    INSERT INTO "Users" ("Id", "Address", "BaseSalary", "CreatedAt", "Email", "FullName", "IsActive", "Password", "Phone", "Role", "SalaryPerShift", "Username")
    VALUES (4, 'Đà Nẵng', 5700000.0, TIMESTAMP '2025-01-01T00:00:00', 'levanc@company.com', 'Lê Văn C', TRUE, '123456', '0912345678', 'Worker', 200000.0, 'worker3');
    INSERT INTO "Users" ("Id", "Address", "BaseSalary", "CreatedAt", "Email", "FullName", "IsActive", "Password", "Phone", "Role", "SalaryPerShift", "Username")
    VALUES (5, 'Hải Phòng', 6000000.0, TIMESTAMP '2025-01-01T00:00:00', 'phamthid@company.com', 'Phạm Thị D', TRUE, '123456', '0934567890', 'Worker', 250000.0, 'worker4');
    INSERT INTO "Users" ("Id", "Address", "BaseSalary", "CreatedAt", "Email", "FullName", "IsActive", "Password", "Phone", "Role", "SalaryPerShift", "Username")
    VALUES (6, 'Cần Thơ', 5800000.0, TIMESTAMP '2025-01-01T00:00:00', 'hoangvane@company.com', 'Hoàng Văn E', TRUE, '123456', '0967890123', 'Worker', 220000.0, 'worker5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    CREATE INDEX "IX_Attendances_ShiftId" ON "Attendances" ("ShiftId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Attendances_UserId_Date" ON "Attendances" ("UserId", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Shifts"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Shifts") + 1,
            nextval(pg_get_serial_sequence('"Shifts"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Users"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Users") + 1,
            nextval(pg_get_serial_sequence('"Users"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802134057_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260802134057_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802141659_AddIndexes') THEN
    CREATE INDEX "IX_Users_Role_IsActive" ON "Users" ("Role", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802141659_AddIndexes') THEN
    CREATE INDEX "IX_Attendances_Date" ON "Attendances" ("Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802141659_AddIndexes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260802141659_AddIndexes', '8.0.11');
    END IF;
END $EF$;
COMMIT;

