// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimekeepingSystem.Models;

#nullable disable

namespace TimekeepingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802141659_AddIndexes")]
    partial class AddIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimekeepingSystem.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("numeric");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TimekeepingSystem.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "06:00 - 12:00",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            Name = "Ca sáng",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Description = "12:00 - 18:00",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            Name = "Ca chiều",
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Description = "18:00 - 22:00",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            Name = "Ca tối",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("TimekeepingSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("SalaryPerShift")
                        .HasColumnType("numeric");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Role", "IsActive");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "VP Công ty",
                            BaseSalary = 0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@company.com",
                            FullName = "Admin",
                            IsActive = true,
                            Password = "admin123",
                            Phone = "0123456789",
                            Role = "Admin",
                            SalaryPerShift = 0m,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hà Nội",
                            BaseSalary = 5700000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nguyenvana@company.com",
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0909123456",
                            Role = "Worker",
                            SalaryPerShift = 250000m,
                            Username = "worker1"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hồ Chí Minh",
                            BaseSalary = 5700000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tranthib@company.com",
                            FullName = "Trần Thị B",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0909987654",
                            Role = "Worker",
                            SalaryPerShift = 250000m,
                            Username = "worker2"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Đà Nẵng",
                            BaseSalary = 5700000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "levanc@company.com",
                            FullName = "Lê Văn C",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0912345678",
                            Role = "Worker",
                            SalaryPerShift = 200000m,
                            Username = "worker3"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hải Phòng",
                            BaseSalary = 6000000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phamthid@company.com",
                            FullName = "Phạm Thị D",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0934567890",
                            Role = "Worker",
                            SalaryPerShift = 250000m,
                            Username = "worker4"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Cần Thơ",
                            BaseSalary = 5800000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoangvane@company.com",
                            FullName = "Hoàng Văn E",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0967890123",
                            Role = "Worker",
                            SalaryPerShift = 220000m,
                            Username = "worker5"
                        });
                });

            modelBuilder.Entity("TimekeepingSystem.Models.Attendance", b =>
                {
                    b.HasOne("TimekeepingSystem.Models.Shift", "Shift")
                        .WithMany("Attendances")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimekeepingSystem.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimekeepingSystem.Models.Shift", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("TimekeepingSystem.Models.User", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
